openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Backend API for managing contacts with auth, email reset, and image uploads.
tags:
  - name: Auth
    description: Authentication & password reset
  - name: Contacts
    description: Contacts CRUD (protected)
servers:
  - url: http://localhost:3000
    description: Local
  - url: https://nodejs-hw-mongodb-4jdp.onrender.com
    description: Production (Render)

paths:
  /contacts:
    get:
      $ref: ../swagger/paths/contacts/get.yaml
    post:
      $ref: ../swagger/paths/contacts/post.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/paths/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/paths/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/contacts/{id}/delete.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer